### ISSUE TITLE
learn.lr_find() is always usung GPU#0 instead of specified device (similar to #1186)

### ISSUE THREAD

**Issue by nikoki** [fastai/fastai#1787]
**Describe the bug**
Having a system with 4 GPUs
Tying to work with GPU#3
The training uses GPU#3 as it should
But `learn.lr_find()` uses GPU#0

**Provide your installation details**

```text
=== Software === 
python        : 3.6.6
fastai        : 1.0.46
fastprogress  : 0.1.20
torch         : 1.0.1.post2
nvidia driver : 390.30
torch cuda    : 9.0.176 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 4
torch devices : 4
  - gpu0      : 11176MB | GeForce GTX 1080 Ti
  - gpu1      : 11178MB | GeForce GTX 1080 Ti
  - gpu2      : 8119MB | GeForce GTX 1080
  - gpu3      : 11178MB | GeForce GTX 1080 Ti

=== Environment === 
platform      : Linux-4.15.0-45-generic-x86_64-with-debian-stretch-sid
distro        : #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019
conda env     : Unknown
python        : /home/nikoki/LearnDL/Learn/.env/bin/python3.6
sys.path      : /home/nikoki/LearnDL/Learn/.env/lib/python36.zip
/home/nikoki/LearnDL/Learn/.env/lib/python3.6
/home/nikoki/LearnDL/Learn/.env/lib/python3.6/lib-dynload
/usr/local/lib/python3.6

/home/nikoki/LearnDL/Learn/.env/lib/python3.6/site-packages
/home/nikoki/LearnDL/Learn/.env/lib/python3.6/site-packages/IPython/extensions
/home/nikoki/.ipython
```

**To Reproduce**
I was playing around with code for Lesson1 - pets
https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson1-pets.ipynb
I wanted to use GPU#3 so I added
` # See how many devices are around`
` torch.cuda.device_count()`
`4`
`# Check which device you are on`
`torch.cuda.current_device()`
`0`
` # Set it to a particular device`
` torch.cuda.set_device(3)`
`# Check which device you are on`
`torch.cuda.current_device()`
`3`
_State of the system is captured on Screenshot 1_

Then after training the model (the rest of the code is the same as Lesson 1)
`learn.fit_one_cycle(5)`
We can see that I have GPU#3 in use - there is the additional process and some memory is occupied.
_State of the system is captured on Screenshot 2_

Then after running the 
`learn.lr_find()`
there is the additional process which uses GPU#0 (its Volatile GPU-Util was showing some load for a few seconds)
_State of the system is captured on Screanshot 3_
**So, this code was using GPU#0 instead of GPU#3** 

**Expected behavior**
Whole code should use only GPU#3

**Screenshots**
Screanshot 1 - State of the system before running the code 
![image](https://user-images.githubusercontent.com/7014947/54019227-f7313400-418a-11e9-98bf-e3b9c30e9dc5.png)

Screenshot 2 - State of the system after training the model 
![image](https://user-images.githubusercontent.com/7014947/54020823-00bc9b00-418f-11e9-864d-8998ee010f7c.png)

Screenshot 3 - State of the system after running `learn.lr_find()`
![image](https://user-images.githubusercontent.com/7014947/54020949-598c3380-418f-11e9-9ec2-b4ebfab57632.png)

**Additional context**
This error caused my code to break yesterday since GPU#0 was occupied and its memory was full so I couldn't run `learn.lr_find()` at all without having 
_CUDA error: out of memory fastai_ error

**Comment by jph00** [comment]
Thanks for the issue. The cause is that `lr_find` saves the state before the dummy training, and then reloads it afterwards. However, it does not reload it in to the correct device, resulting in a redundant copy of the model on GPU 0. We can probably fix this by having `load` default to loading in to the current device, although we'll need to do some testing.

**Comment by sgugger** [comment]
The problem was that `torch.cuda.set_device` doesn't update `defaults.device` which is what we use internally. Note that you have to set this before defining any `DataBunch` or it's going to use the wrong device.
