### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:24

### ISSUE THREAD

**Issue by timpal0l** [fastai/fastai#1835]
After training a language model and playing with it by making some predictions, I sometimes get this error below. 
```
In [33]: lm.beam_search('hello world', n_words=100, temperature=0.7)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-33-c0cbcf0b5600> in <module>
----> 1 lm.beam_search('hello world', n_words=100, temperature=0.7)

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/fastai/text/learner.py in beam_search(self, text, n_words, no_unk, top_k, beam_sz, temperature, sep, decoder)
    137         "Return the `n_words` that come after `text` using beam search."
    138         ds = self.data.single_dl.dataset
--> 139         self.model.reset()
    140         xb, yb = self.data.one_item(text)
    141         nodes = None

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/fastai/text/models/awd_lstm.py in reset(self)
    157     def reset(self):
    158         for c in self.children():
--> 159             if hasattr(c, 'reset'): c.reset()
    160 
    161 def awd_lstm_lm_split(model:nn.Module) -> List[nn.Module]:

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/fastai/text/models/awd_lstm.py in reset(self)
    133         [r.reset() for r in self.rnns if hasattr(r, 'reset')]
    134         if self.qrnn: self.hidden = [self._one_hidden(l) for l in range(self.n_layers)]
--> 135         else: self.hidden = [(self._one_hidden(l), self._one_hidden(l)) for l in range(self.n_layers)]
    136 
    137 class LinearDecoder(nn.Module):

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/fastai/text/models/awd_lstm.py in <listcomp>(.0)
    133         [r.reset() for r in self.rnns if hasattr(r, 'reset')]
    134         if self.qrnn: self.hidden = [self._one_hidden(l) for l in range(self.n_layers)]
--> 135         else: self.hidden = [(self._one_hidden(l), self._one_hidden(l)) for l in range(self.n_layers)]
    136 
    137 class LinearDecoder(nn.Module):

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/fastai/text/models/awd_lstm.py in _one_hidden(self, l)
    122         "Return one hidden state."
    123         nh = (self.n_hid if l != self.n_layers - 1 else self.emb_sz) // self.n_dir
--> 124         return one_param(self).new(1, self.bs, nh).zero_()
    125 
    126     def select_hidden(self, idxs):

RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMath.cu:24

```

Once this error has happend I cant do anything. I tried to save or export the model. However when using export the following error:

```
In [34]: lm.export()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-34-d7db03ee751b> in <module>
----> 1 lm.export()

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/fastai/basic_train.py in export(self, fname, destroy)
    233         #layer_groups -> need to find a way
    234         #TO SEE: do we save model structure and weights separately?
--> 235         with ModelOnCPU(self.model) as m:
    236             state['model'] = m
    237             xtra = dict(normalize=self.data.norm.keywords) if getattr(self.data, 'norm', False) else {}

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/fastai/torch_core.py in __enter__(self)
    266     def __enter__(self):
    267         self.device = one_param(self.model).device
--> 268         return self.model.cpu()
    269     def __exit__(self, type, value, traceback):
    270         self.model = self.model.to(self.device)

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in cpu(self)
    266             Module: self
    267         """
--> 268         return self._apply(lambda t: t.cpu())
    269 
    270     def type(self, dst_type):

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    185     def _apply(self, fn):
    186         for module in self.children():
--> 187             module._apply(fn)
    188 
    189         for param in self._parameters.values():

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    185     def _apply(self, fn):
    186         for module in self.children():
--> 187             module._apply(fn)
    188 
    189         for param in self._parameters.values():

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    191                 # Tensors stored in modules are graph leaves, and we don't
    192                 # want to create copy nodes, so we have to unpack the data.
--> 193                 param.data = fn(param.data)
    194                 if param._grad is not None:
    195                     param._grad.data = fn(param._grad.data)

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in <lambda>(t)
    266             Module: self
    267         """
--> 268         return self._apply(lambda t: t.cpu())
    269 
    270     def type(self, dst_type):

RuntimeError: CUDA error: device-side assert triggered
```
I trained the model for about 20 hours, so it's a bit frustrating that you cannot even save it. Looks like some side effect from predict/beam_search causing alot of trouble related to Cuda.

OS: Ubuntu 18.04 (64-bit)
Latest fastai and pytorch (fresh install from anaconda today)

**Comment by sgugger** [comment]
A CUDA device-side assert error usually means there has been a bad index error on a Tensor on the GPU. You can't recover from it and need to restart the notebook. That's not linked to fastai.
After a long training, it's best practice to immediately save your model before anything else can go wrong. 

As for the cause of the error, I just double-checked the function and it worked in my case, so we would need a reproducible example to be able to help. Make sure you have the latest version of fastai too, as the reason of your problem may be a bug that has already been fixed.

Closing for now, please reopen if the problem persists with installation details and code to fully reproduce the bug.
