### ISSUE TITLE
Load state dict error when using fit_one_cycle

### ISSUE THREAD

**Issue by JosephPB** [fastai/fastai#1862]
**Describe the bug**

When training a `language_model_learner` using the code on the [ulmfit-multilingual repo](https://github.com/n-waves/ulmfit-multilingual), I find that there is an error when running `fit_one_cycle` regarding loading the state dict, but I do not get this error with the `fit` function.

**Provide your installation details**
```
=== Software ===
python        : 3.6.8
fastai        : 1.0.46.dev0
fastprogress  : 0.1.20
torch         : 1.1.0a0+929cd23
nvidia driver : 384.130
torch cuda    : 8.0.61 / is available
torch cudnn   : 7104 / is enabled

=== Hardware ===
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11439MB | Tesla K80

=== Environment ===
platform      : Linux-4.4.0-1075-aws-x86_64-with-debian-stretch-sid
distro        : Ubuntu 16.04 xenial
conda env     : fastai_ulm
python        : /home/ubuntu/anaconda3/envs/fastai_ulm/bin/python
sys.path      :
/home/ubuntu/src/cntk/bindings/python
/home/ubuntu/pytorch/build
/efs/data/jpb/Detectron/Detectron
/home/ubuntu/anaconda3/envs/fastai_ulm/lib/python36.zip
/home/ubuntu/anaconda3/envs/fastai_ulm/lib/python3.6
/home/ubuntu/anaconda3/envs/fastai_ulm/lib/python3.6/lib-dynload
/home/ubuntu/.local/lib/python3.6/site-packages
/home/ubuntu/anaconda3/envs/fastai_ulm/lib/python3.6/site-packages
/home/ubuntu/anaconda3/envs/fastai_ulm/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg
/home/ubuntu/anaconda3/envs/fastai_ulm/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg
/home/ubuntu/anaconda3/envs/fastai_ulm/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg
/efs/data/jpb/fastai/fastai
```

**To Reproduce**

`learn = lm.create_lm_learner(data_lm)` from the `pretrain_lm.py` script [here](https://github.com/n-waves/ulmfit-multilingual/blob/master/ulmfit/pretrain_lm.py) which has the following args:
```
Training args:  {'clip': 0.12, 'alpha': 2, 'beta': 1} dps:  {'output_p': 0.25, 'hidden_p': 0.1, 'input_p': 0.2, 'embed_p': 0.02, 'weight_p': 0.15}
```

After running:
```
learn.fit_one_cycle(1,1e-2)
```
gives the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-e85309452eba> in <module>
----> 1 learn.fit_one_cycle(1,1e-2)

/efs/data/jpb/fastai/fastai/fastai/train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, wd, callbacks, tot_epochs, start_epoch)
     20     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor, pct_start=pct_start, tot_epochs=tot_epochs, 
     21                                        start_epoch=start_epoch))
---> 22     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     23 
     24 def lr_find(learn:Learner, start_lr:Floats=1e-7, end_lr:Floats=10, num_it:int=100, stop_div:bool=True, wd:float=None):

/efs/data/jpb/fastai/fastai/fastai/basic_train.py in fit(self, epochs, lr, wd, callbacks)
    175         callbacks = [cb(self) for cb in self.callback_fns] + listify(callbacks)
    176         fit(epochs, self.model, self.loss_func, opt=self.opt, data=self.data, metrics=self.metrics,
--> 177             callbacks=self.callbacks+callbacks)
    178 
    179     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

/efs/data/jpb/fastai/fastai/fastai/utils/mem.py in wrapper(*args, **kwargs)
    104 
    105         try:
--> 106             return func(*args, **kwargs)
    107         except Exception as e:
    108             if ("CUDA out of memory" in str(e) or

/efs/data/jpb/fastai/fastai/fastai/basic_train.py in fit(epochs, model, loss_func, opt, data, callbacks, metrics)
     98         exception = e
     99         raise
--> 100     finally: cb_handler.on_train_end(exception)
    101 
    102 loss_func_name2activ = {'cross_entropy_loss': F.softmax, 'nll_loss': torch.exp, 'poisson_nll_loss': torch.exp,

/efs/data/jpb/fastai/fastai/fastai/callback.py in on_train_end(self, exception)
    289     def on_train_end(self, exception:Union[bool,Exception])->None:
    290         "Handle end of training, `exception` is an `Exception` or False if no exceptions during training."
--> 291         self('train_end', exception=exception)
    292 
    293 class AverageMetric(Callback):

/efs/data/jpb/fastai/fastai/fastai/callback.py in __call__(self, cb_name, call_mets, **kwargs)
    212         "Call through to all of the `CallbakHandler` functions."
    213         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]
--> 214         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
    215 
    216     def set_dl(self, dl:DataLoader):

/efs/data/jpb/fastai/fastai/fastai/callback.py in <listcomp>(.0)
    212         "Call through to all of the `CallbakHandler` functions."
    213         if call_mets: [getattr(met, f'on_{cb_name}')(**self.state_dict, **kwargs) for met in self.metrics]
--> 214         return [getattr(cb, f'on_{cb_name}')(**self.state_dict, **kwargs) for cb in self.callbacks]
    215 
    216     def set_dl(self, dl:DataLoader):

/efs/data/jpb/fastai/fastai/fastai/callbacks/tracker.py in on_train_end(self, **kwargs)
    100         "Load the best model."
    101         if self.every=="improvement" and (self.learn.path/f'{self.learn.model_dir}/{self.name}.pth').is_file():
--> 102             self.learn.load(f'{self.name}')
    103 
    104 class ReduceLROnPlateauCallback(TrackerCallback):

/efs/data/jpb/fastai/fastai/fastai/basic_train.py in load(self, name, device, strict, with_opt, purge)
    236     def load(self, name:PathOrStr, device:torch.device=None, strict:bool=True, with_opt:bool=None, purge:bool=True):
    237         "Load model and optimizer state (if `with_opt`) `name` from `self.model_dir` using `device`."
--> 238         if purge: self.purge(clear_opt=ifnone(with_opt, False))
    239         if device is None: device = self.data.device
    240         state = torch.load(self.path/self.model_dir/f'{name}.pth', map_location=device)

/efs/data/jpb/fastai/fastai/fastai/basic_train.py in purge(self, clear_opt)
    291         self.callbacks = [load_callback(c,s, self) for c,s in cb_state.items()]
    292         if not clear_opt and 'opt' in state:
--> 293             self.opt = OptimWrapper.load_with_state_and_layer_group(state['opt'], self.layer_groups)
    294         del state
    295         gc.collect()

/efs/data/jpb/fastai/fastai/fastai/callback.py in load_with_state_and_layer_group(cls, state, layer_groups)
    128                      bn_wd=state['bn_wd'])
    129         res._mom,res._beta = state['mom'],state['beta']
--> 130         res.load_state_dict(state['opt_state'])
    131         return res
    132 

~/anaconda3/envs/fastai_ulm/lib/python3.6/site-packages/torch/optim/optimizer.py in load_state_dict(self, state_dict)
    112         saved_lens = (len(g['params']) for g in saved_groups)
    113         if any(p_len != s_len for p_len, s_len in zip(param_lens, saved_lens)):
--> 114             raise ValueError("loaded state dict contains a parameter group "
    115                              "that doesn't match the size of optimizer's group")
    116 

ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```

**Additional Information**

It is worth noting that no error appears when running `fit`

**Comment by sgugger** [comment]
This looks very similar to #1849 so I think this has been solved.

**Comment by JosephPB** [comment]
Okay thanks, I've pulled the latest dev version and it's working now

**Comment by JosephPB** [comment]
Sorry, now when running 

`print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))`

I get the following error"
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-135dd315cd3b> in <module>
----> 1 print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

<ipython-input-38-135dd315cd3b> in <genexpr>(.0)
----> 1 print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

/efs/data/jpb/fastai/fastai/fastai/text/learner.py in predict(self, text, n_words, no_unk, temperature, min_p, sep, decoder)
    119         ds = self.data.single_dl.dataset
    120         self.model.reset()
--> 121         xb,yb = self.data.one_item(text)
    122         new_idx = []
    123         for _ in range(n_words): #progress_bar(range(n_words), leave=False):

/efs/data/jpb/fastai/fastai/fastai/basic_data.py in one_item(self, item, detach, denorm, cpu)
    178         "Get `item` into a batch. Optionally `detach` and `denorm`."
    179         ds = self.single_ds
--> 180         with ds.set_item(item):
    181             return self.one_batch(ds_type=DatasetType.Single, detach=detach, denorm=denorm, cpu=cpu)
    182 

~/anaconda3/envs/fastai_ulm/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

/efs/data/jpb/fastai/fastai/fastai/data_block.py in set_item(self, item)
    594     def set_item(self,item):
    595         "For inference, will briefly replace the dataset with one that only contains `item`."
--> 596         self.item = self.x.process_one(item)
    597         yield None
    598         self.item = None

/efs/data/jpb/fastai/fastai/fastai/data_block.py in process_one(self, item, processor)
     80         if processor is not None: self.processor = processor
     81         self.processor = listify(self.processor)
---> 82         for p in self.processor: item = p.process_one(item)
     83         return item
     84 

/efs/data/jpb/fastai/fastai/fastai/text/data.py in process_one(self, item)
    286 
    287     def process_one(self, item):
--> 288         return self.tokenizer._process_all_1(_join_texts([item], self.mark_fields, self.include_bos, self.include_eos))[0]
    289 
    290     def process(self, ds):

AttributeError: 'TokenizeProcessor' object has no attribute 'include_bos'
```

**Comment by sgugger** [comment]
Did you use `load_data` to load your data? It might be linked to that since the functionality was added recently. You can hack your way around it by adding the attributes manually to `data.single_ds.x.processor`. I think the tokenize processor might be the first one, so you would go:
```
data.single_ds.x.processor[0].include_bos=True
data.single_ds.x.processor[0].include_eos=False
```

**Comment by JosephPB** [comment]
No I used the following function:

```
    def load_wiki_data(self, bs=70):
        self.model_dir.mkdir(exist_ok=True, parents=True)
        trn_path = self.dataset_path / f'{self.lang}.wiki.train.tokens'
        val_path = self.dataset_path / f'{self.lang}.wiki.valid.tokens'
        tst_path = self.dataset_path / f'{self.lang}.wiki.test.tokens'
        for path_ in [trn_path, val_path, tst_path]:
            assert path_.exists(), f'Error: {path_} does not exist.'

        args = self.tokenizer_to_fastai_args(sp_data_func=self.load_train_text, use_moses=False)

        data_lm = self.lm_databunch("lm",
                          train_df=read_wiki_articles(trn_path),
                          valid_df=read_wiki_articles(val_path),
                          classes=None,
                          bs=bs,
                          text_cols='texts',
                          bptt=self.bptt,
                          **args)

        itos, stoi, trn_path = data_lm.vocab.itos, data_lm.vocab.stoi, data_lm.path
        print('Size of vocabulary:', len(itos))
        #print('First 20 words in vocab:', data_lm.vocab.itos[:20])
        return data_lm
```

Okay, should I add this before training, as it's not working if I call it after the model is trained and before I predict?
