### ISSUE TITLE
Distributed Training not working.

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastai#3498]
The script from `nbs/examples/distrib.py` is not working.
First, the mixed precision cb is now just `fp_16` as native has been integrated to fastai.
Second, I am getting a `RuntimeError: No grad accumulator for a saved leaf!` that I am not sure how to interpret.
Currently, for training on a multi GPU machine, the `parallel_ctx()` is working, but it is not as fast as DDP.

It is working, but when passing `parallel_ctx(bn_sync=False)`

**Comment by Shravan1804** [comment]
This issue remains open at least on my side. Any ideas how to fix it?

**Comment by tinku99** [comment]
Try: 
NCCL_P2P_LEVEL=NVL accelerate launch distrib.py

**Comment by eihli** [comment]
Just ran `accelerate launch nbs/examples/distrib.py` on the most up-to-date master (b273fbb32d075ef1d6fd372687b5f56564cead9) with 4 GPUs and didn't get any error. I think this can be closed. Maybe in the past 2 years since this was opened, whatever was causing the issue was fixed.
